apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx 
    name: webserver
    volumeMounts:
    - mountPath: /giropops  #Local da montagem
      name: primeiro-emptydir # Nome
    resources: 
      # Limite maximo
      limits:
        cpu: "1"
        memory: "128Mi"

      # Recurso Garantido 
      requests:
        cpu: "0.5"
        memory: "64Mi"

  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: #Definir o volume declarado acima
  - name: primeiro-emptydir #NMesmo nome o acima
    emptyDir: # Definição do emptydir
      sizeLimit: 256Mi # Limitação
