apiVersion: v1
kind: Pod
metadata:
  namespace: treinamento-ch2
  labels:
    run: pod-comportado
  name: pod-comportado
spec:
  containers:
  - image: polinux/stress
    name: pod-comportado
    command: ["/bin/sh", "-c"]
    args:
    - stress --vm 1 --vm-bytes 250M --vm-hang 1
    resources:
      limits:
        memory: "400Mi"
      requests:
        memory: "100Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
