apiVersion: apps/v1
kind: Deployment
metadata:
  labels: # Labels do deployment
    app:  nginx-deployment # Label do deployment
  name: nginx-deployment # Nome do deployment
spec:
  replicas: 1 # Número de pods que devem estar em execução
  selector: # Seleciona os pods que devem ser atualizados
    matchLabels: # Seleciona os pods que devem ser atualizados
      app: nginx-deployment # Label do deployment 
  strategy: {}
  template:
    metadata: 
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.19.1 # Imagem do container
        name: nginx # Nome do container
        resources: 
          limits: # Limites de recursos máximos
            cpu: 0.5 # CPU máxima
            memory: 256Mi # Memória máxima
          requests: # Recursos solicitados mínimos
            cpu: 0.25 # CPU mínima
            memory: 128Mi # Memória mínima  
